.TH "Dialog" 3 "Mon Jan 2 2023" "Brogrammers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dialog \- In this class, there are all processes that will be run in case of error occur\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDialog\fP (QWidget *parent=nullptr, QString message='Failed')"
.br
.RI "This is a Page that will appear in case of errors\&. "
.in -1c
.SH "Detailed Description"
.PP 
In this class, there are all processes that will be run in case of error occur\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dialog::Dialog (QWidget * parent = \fCnullptr\fP, QString message = \fC'Failed'\fP)\fC [explicit]\fP"

.PP
This is a Page that will appear in case of errors\&. If the user enters any invalid data during login or adding new professors or anything else this page will appear\&. 
.PP
\fBAuthor\fP
.RS 4
Amir Hesham 
.RE
.PP
\fBCopyright\fP
.RS 4
Brogrammers\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Brogrammers from the source code\&.
