.TH "MainWindow" 3 "Mon Jan 2 2023" "Brogrammers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- In this class, there are all processes and actions all over the program\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
In this class, there are all processes and actions all over the program\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Brogrammers from the source code\&.
