.TH "User" 3 "Mon Jan 2 2023" "Brogrammers" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User \- In this class, there are all features and relations between Admins, Students and Professors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <user\&.h>\fP
.PP
Inherited by \fBAdmin\fP, \fBProfessor\fP, and \fBStudent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP (std::string name, std::string email, std::string phone, std::string department, int age)"
.br
.RI "\fBUser\fP Class Features\&. "
.ti -1c
.RI "\fBUser\fP (std::string name, std::string email, std::string phone, int age)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.RI "Get the \fBUser\fP's Name\&. "
.ti -1c
.RI "std::string \fBgetEmail\fP () const"
.br
.RI "Get the \fBUser\fP's Email\&. "
.ti -1c
.RI "std::string \fBgetPhone\fP () const"
.br
.RI "Get the \fBUser\fP's Phone\&. "
.ti -1c
.RI "std::string \fBgetDepartment\fP () const"
.br
.RI "Get the \fBUser\fP's Department\&. "
.ti -1c
.RI "int \fBgetAge\fP () const"
.br
.RI "Get the \fBUser\fP's Age\&. "
.in -1c
.SH "Detailed Description"
.PP 
In this class, there are all features and relations between Admins, Students and Professors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "User::User (std::string name, std::string email, std::string phone, std::string department, int age)"

.PP
\fBUser\fP Class Features\&. This class is used to link the data of Users to the database\&. 
.PP
\fBAuthor\fP
.RS 4
Amir Hesham 
.RE
.PP
\fBCopyright\fP
.RS 4
Brogrammers\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int User::getAge () const"

.PP
Get the \fBUser\fP's Age\&. 
.PP
\fBParameters\fP
.RS 4
\fINULL\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBUser\fP's Age 
.RE
.PP

.SS "std::string User::getDepartment () const"

.PP
Get the \fBUser\fP's Department\&. 
.PP
\fBParameters\fP
.RS 4
\fINULL\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBUser\fP's Department 
.RE
.PP

.SS "std::string User::getEmail () const"

.PP
Get the \fBUser\fP's Email\&. 
.PP
\fBParameters\fP
.RS 4
\fINULL\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBUser\fP's Email 
.RE
.PP

.SS "std::string User::getName () const"

.PP
Get the \fBUser\fP's Name\&. 
.PP
\fBParameters\fP
.RS 4
\fINULL\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBUser\fP's Name 
.RE
.PP

.SS "std::string User::getPhone () const"

.PP
Get the \fBUser\fP's Phone\&. 
.PP
\fBParameters\fP
.RS 4
\fINULL\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBUser\fP's Phone 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Brogrammers from the source code\&.
